=== bkm71A/liechtenstein/incheck-project/trunk/insite-ng/server/build/test-data/data_channel.dtd
<!ELEMENT dataset (dam*,sensor*, channel*)>

<!ELEMENT dam EMPTY>
<!ATTLIST dam
    ID CDATA #REQUIRED
    SERIAL_NUMBER CDATA #REQUIRED
    DESCRIPTION CDATA #REQUIRED
    DEVICE_TYPE CDATA #REQUIRED
>

<!ELEMENT sensor EMPTY>
<!ATTLIST sensor
    ID CDATA #REQUIRED
    DAM_ID CDATA #REQUIRED
    SENSOR_TYPE_ID CDATA #REQUIRED
    NAME CDATA #REQUIRED
    COMMENTS CDATA #IMPLIED
>

<!ELEMENT channel EMPTY>
<!ATTLIST channel
    ID CDATA #REQUIRED
    SENSOR_ID CDATA #REQUIRED
    DEVICE_CHANNEL_ID CDATA #REQUIRED
    CHANNEL_TYPE_ID CDATA #REQUIRED
    CHANNEL_MEASURE_TYPE_ID CDATA #REQUIRED
    COMMENTS CDATA  #IMPLIED
>

=== bkm71A/liechtenstein/incheck-project/trunk/insite-ng/server/build/test-data/data_channel.xml
<!DOCTYPE dataset SYSTEM "data_channel.dtd">
<dataset>
    <dam ID="-1" SERIAL_NUMBER="00:D0:69:41:55:CA" DESCRIPTION="Test Data Acquisition Module" DEVICE_TYPE="-1"/>
    <sensor ID="-1" DAM_ID="-1" SENSOR_TYPE_ID="-1" NAME="Sensor Test #1"/>
    <sensor ID="-2" DAM_ID="-1" SENSOR_TYPE_ID="-3" NAME="Sensor Test #2"/>
    <channel ID="-1" SENSOR_ID="-1" DEVICE_CHANNEL_ID="1" CHANNEL_TYPE_ID="0" CHANNEL_MEASURE_TYPE_ID="1"/>
    <channel ID="-2" SENSOR_ID="-1" DEVICE_CHANNEL_ID="2" CHANNEL_TYPE_ID="0" CHANNEL_MEASURE_TYPE_ID="2"/>
    <channel ID="-3" SENSOR_ID="-2" DEVICE_CHANNEL_ID="3" CHANNEL_TYPE_ID="1" CHANNEL_MEASURE_TYPE_ID="1"/>
    <channel ID="-4" SENSOR_ID="-2" DEVICE_CHANNEL_ID="4" CHANNEL_TYPE_ID="1" CHANNEL_MEASURE_TYPE_ID="2"/>
    <channel ID="-5" SENSOR_ID="-2" DEVICE_CHANNEL_ID="5" CHANNEL_TYPE_ID="0" CHANNEL_MEASURE_TYPE_ID="1"/>
</dataset>
